#!/bin/sh -e

pushd po/
../tools/tmplgettext "^.*\.html$" ../template >tmp-html-x.pot
msguniq tmp-html-x.pot >vdradmin.pot

xgettext --from-code=ISO-8859-1 -L Perl ../vdradmind.pl -j -o vdradmin.pot
xgettext --from-code=ISO-8859-1 -L Perl ../template/i18n.pl -j -o vdradmin.pot
rm tmp-*.pot
popd


for LANG in de es fi fr ; do
    if msgmerge po/$LANG.po po/vdradmin.pot >temp.po ; then
        mv -f temp.po po/$LANG.po
    else
        echo "error merging po/$LANG.po and po/vdradmin.pot"
    fi
done
